theme: jekyll-theme-cayman
title: "PanAf20K:  A Large Video Dataset for Wild Ape Detection & Behaviour Analysis"
description: "Otto Brookes, Majid Mirmehdi, Colleen Stephens, Maureen McCarthy, Mizuki Murai, Emmanuelle Normand, Virginie Vergnes, Amelia Meier, Juan Lapuente Roman Wittig, Dervla Dowd, Sorrel Jones, Vera Leinert, Erin Wessling,  Katherine Corogenes,  Klaus Zuberbühler, Kevin Lee, Samuel Angedakin, Kevin Langergraber, Paula Dieguez, Nuria Maldonado, Christophe Boesch, Mimi Arandjelovic, Hjalmar Kühl, Tilo Burghardt"
show_downloads: true
